-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 15:30:22 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `LivBoulder` DEFAULT CHARACTER SET utf8 ;
USE `LivBoulder` ;

-- -----------------------------------------------------
-- Table `mydb`.`Account`
-- -----------------------------------------------------
drop table if exists `Account`;
CREATE TABLE  `Account` (
  `accountNumber` INT NOT NULL,
  `userName` VARCHAR(45) NOT NULL,
  `passWord` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `bio` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NOT NULL,
  `activityNumber` INT NULL,
  PRIMARY KEY (`accountNumber`),
  UNIQUE INDEX `accountNumber_UNIQUE` (`accountNumber` ASC) VISIBLE)
ENGINE = InnoDB;
/*insert data into account*/

-- -----------------------------------------------------
-- Table `mydb`.`Activities`
-- -----------------------------------------------------
drop table if exists `Activities`;
CREATE TABLE `Activities` (
  `activity` VARCHAR(45) NOT NULL,
  `activitynumber` INT NOT NULL,
  `description` VARCHAR(2000) NOT NULL,  
  `image_index` INT NULL,
  `account_accountNumber` INT NULL,
  PRIMARY KEY (`activitynumber`),
  INDEX `fk_activities_account_idx` (`account_accountNumber` ASC) VISIBLE,
  CONSTRAINT `fk_activities_account`
    FOREIGN KEY (`account_accountNumber`)
    REFERENCES `LivBoulder`.`Account` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
/*insert data into activities*/
insert into `Activities`(`activity`,`activitynumber`,`description`)values
('Pedego Electric Bike Tour',1,'Take a 3-hour electric bike tour
and explore historic downtown Boulder,
Boulder Canyon, Chataqua, and more!
'),
('Front Range Anglers Fishing',2,'Take a guided fly fishing expedition for 
Trout in Boulder and along the Front Range!'),
('Hot Air Balloon Flight',3,'Enjoy gorgeous views of moutain scenery,
Colorados plains, and wildlife as far as the
eye can see as your soar through the sky
in a hot air balloon!'),
('The Boulder Creek Path',4,'Go for a stroll or hop on your bike as you
travel along the Boulder Creek Path! This path
follows the gorgeous Boulder Creek and allows
for multiple pitstops at some of Boulders 
finest locations.'),
('Mount Sanitas Trail',5,'This is a 90 minute hike with views that allow 
you to see almost all the way to Kansas! Its rated
as a moderate difficulty, so make sure to bring water!
'),
('Royal Arch Trail','6','A challenging hike with an absolutley stunning
reward at the top. Dont be confused by the false
summit - theres still an extra half mile from that
point!'),
('Valmont Bike Park',7,'No matter your experience in mountain biking,
the Valmont Bike Park has what youre looking for!
Enjoy a day in the sun and some gnarly rides!'),
('Flatiron Golf Course',8,'Enjoy Boulders premier golf course with a wonderful 
view of the Flatirons! Course regulars love the 
moderate challenge of the course and the friendly
staff.'),
('Boulder Ale Trail',9,'15 miles, 12 breweries, and 0 cars! The Boulder
Ale trail is the perfect way to enjoy your two favorite
things in one of the nations biggest brewing
cities!'),
('First and Second Flatiron Hike',10,'Hike up Boulders most prominent features - the
Flatirons! This is a 2.6 mile round trip hike that 
offers a gorgeous panoramic view at the top.'),
('Sombrero Ranch Horseback Riding',11,'Its time to hit the powder, and dont expect to come
back without a smile on your face! The Eldora Ski
Resort is known throughout Colorado as one of
the best places for skiing, and its a short ride from
Boulder.'),
('Eldora Ski Resort',12,"It's time to hit the powder, and don't expect to come
back without a smile on your face! The Eldora Ski
Resort is known throughout Colorado as one of
the best places for skiing, and it's a short ride from
Boulder."),
('Bear Peak Trail',13,'A must-do hike for anyone in Colorado! The trail is 
challenging, but the views seen throughout the hike 
are truly stunning. Plus, a good workout means you 
can kick back an extra beer after!'),
('Boulder Creek Tubing',14,'Kick back, relax, and enjoy a wonderful time tubing
down the Boulder Creek! While some take to the 
creek in the Winter as a show of grit, we recommend 
this as a Summer activity.'),
('Boulder Resevoir Paddleboarding',15,'The cool breeze in your hair, the warm sun on 
your shoulders — there’s no better way to enjoy a 
summer day than cruising along the glittering waters 
of Boulder Reservoir on a stand-up paddleboard.'),
('Flower Picking',16,'Longs Gardens in Boulder allows visitors to pick
and dig up their very own flowers! Were betting this
is an experience that youve never had before!');
-- -----------------------------------------------------
-- Table `mydb`.`Questions`
-- -----------------------------------------------------
drop table if exists `Questions`;
CREATE TABLE  `Questions` (
  `water` TINYINT NULL,
  `biking` TINYINT NULL,
  `hiking` TINYINT NULL,
  `lots_of_exercise` TINYINT NULL,
  `competitive` TINYINT NULL,
  `easy` TINYINT NULL,
  `long` TINYINT NULL,
  `adventurous` TINYINT NULL,
  `close` TINYINT NULL,
  `activityNumber` INT NOT NULL ,
  `account_accountNumber` INT,
  PRIMARY KEY (`activityNumber`),
  INDEX `fk_questions_account1_idx` (`account_accountNumber` ASC) VISIBLE,

  CONSTRAINT `fk_questions_account1`
    FOREIGN KEY (`account_accountNumber`)
    REFERENCES `LivBoulder`.`Account` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
/*insert into questions*/
insert into `Questions` (`water`,`biking`,`hiking`,`lots_of_exercise`,`competitive`,`easy`,`long`,`adventurous`,`close`,`activityNumber`)values
(0,1,0,0,0,1,0,0,1,1),
(1,0,0,0,0,1,1,0,1,2),
(0,0,0,0,0,1,1,1,0,3),
(1,1,0,0,0,1,0,0,1,4),
(0,0,1,1,0,0,1,1,1,5),
(0,0,1,1,0,0,1,1,1,6),
(0,1,0,1,1,1,0,0,1,7),
(0,0,0,0,1,1,1,0,1,8),
(0,1,0,0,0,1,1,0,1,9),
(0,0,1,1,0,0,1,1,1,10),
(0,0,0,0,0,1,0,1,0,11),
(0,0,0,1,1,0,1,1,0,12),
(0,0,1,1,0,0,1,1,1,13),
(1,0,0,0,0,1,0,0,1,14),
(1,0,0,1,0,1,0,0,1,15),
(0,0,0,0,0,1,0,0,0,16);
-- -----------------------------------------------------
-- Table `mydb`.`Quiz`
-- -----------------------------------------------------
drop table if exists `Quiz`;
CREATE TABLE  `Quiz` (
  `questions_resultNumber` INT NOT NULL,
  `Account_accountNumber` INT NOT NULL,
  PRIMARY KEY (`questions_resultNumber`, `Account_accountNumber`),
  INDEX `fk_Quiz_questions1_idx` (`questions_resultNumber` ASC) VISIBLE,
  INDEX `fk_Quiz_Account1_idx` (`Account_accountNumber` ASC) VISIBLE,
  CONSTRAINT `fk_Quiz_questions1`
    FOREIGN KEY (`questions_resultNumber`)
    REFERENCES `mydb`.`Questions` (`activityNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Quiz_Account1`
    FOREIGN KEY (`Account_accountNumber`)
    REFERENCES `LivBoulder`.`Account` (`accountNumber`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
